# Useful script to generate a plugin archive (ZIP generated by CPack) of a cmake plugin project
# The generated archive contains the plugin manifest at its root and the plugin binary (with its runtime dependencies) in a subfolder, so it can be extracted directly into a host's plugins directory.
# Set cmake_opt variable before calling this script to set cmake defines (must at least enable the plugin build, its install rules and the plugin CPack target of the project)
# Set selfFolderPath variable before calling this script to the absolute path of the calling script
# Set pluginName variable before calling this script to the name of the plugin cmake project (used for the archive base name). Can be overridden on the command line with the -p option
# Set versionVarName variable before calling this script to the name of the cmake variable holding the plugin version in the root CMakeLists.txt (defaults to the first *_VERSION variable found)
# The following functions can be defined before including this script:
#   extend_gpa_fnc_help() -> Called when -h is requested. No return value
#   extend_gpa_fnc_defaults() -> Called when default values are initialized. Override default global values from the function. No return value
#     - default_VisualGenerator -> Visual Studio version to use. Default is "Visual Studio 17 2022"
#     - default_VisualToolset -> Visual Studio toolset to use. Default is "v143"
#     - default_VisualToolchain -> Visual Studio toolchain to use. Default is "x64"
#     - default_buildArch -> Default build architecture to use. Default is the host architecture (x86, x64, arm64, etc.)
#     - default_betaTagName -> The tag to use before the 4th digit for beta releases. Default is "-beta"
#   extend_gpa_fnc_unhandled_arg() -> Called when an unhandled argument is found. Return the count of consumed args
#   extend_gpa_fnc_postparse() -> Called after parsing all arguments. No return value
#   extend_gpa_fnc_props_summary() -> Called just before invoking gen_cmake when printing build properties summary. No return value

GPA_GeneratorVersion="1.0"

echo "Plugin Archive Generator version $GPA_GeneratorVersion"
echo ""

# Check if selfFolderPath is defined
if [ -z "$selfFolderPath" ]; then
	echo "ERROR: selfFolderPath variable not set. Please set it before calling this script."
	exit 1
fi
# Check if selfFolderPath is absolute
if [[ "$selfFolderPath" != /* ]]; then
	echo "ERROR: selfFolderPath variable is not absolute. Please set it to an absolute path before calling this script."
	exit 1
fi
# Check if selfFolderPath is a directory
if [ ! -d "$selfFolderPath" ]; then
	echo "ERROR: selfFolderPath variable is not a directory. Please set it to an absolute path to a directory before calling this script."
	exit 1
fi
# Locally store selfFolderPath for later use
bu_gpa_callerFolderPath="$selfFolderPath"
# Check if bu_gpa_callerFolderPath ends with /
if [[ "${bu_gpa_callerFolderPath: -1}" != "/" ]]; then
	bu_gpa_callerFolderPath="$bu_gpa_callerFolderPath/"
fi

# Get absolute folder for this script
bu_gpa_selfFolderPath="`cd "${BASH_SOURCE[0]%/*}"; pwd -P`/" # Command to get the absolute path

# Include utils functions
. "${bu_gpa_selfFolderPath}utils.sh"

# Sanity checks
envSanityChecks "grep"

# Include config file functions
. "${bu_gpa_selfFolderPath}load_config_file.sh"

# Default values
default_VisualGenerator="Visual Studio 17 2022"
default_VisualToolset="v143"
default_VisualToolchain="x64"
default_betaTagName="-beta"

# Check for defaults override
if [[ $(type -t extend_gpa_fnc_defaults) == function ]]; then
	extend_gpa_fnc_defaults
fi

#
cmake_path=""
cmake_generator=""
platform=""
default_arch=""
declare -a arch=()
toolset=""
outputFolderBasePath="_package"
deliverablesFolder="_deliverables"
verbose=0
declare -a supportedArchs=()

getCmakePath cmake_path

if isMac; then
	generator="Xcode"
	# If a default architecture is set, use it. Otherwise, use the host architecture
	if [ -z "$default_buildArch" ]; then
		getMachineArch default_arch
	else
		default_arch="$default_buildArch"
	fi
	supportedArchs+=("x64")
	supportedArchs+=("arm64")
else
	# Use cmake from the path
	if isWindows; then
		generator="$default_VisualGenerator"
		toolset="$default_VisualToolset"
		toolchain="$default_VisualToolchain"
		default_arch="$default_buildArch"
		supportedArchs+=("x86")
		supportedArchs+=("x64")
	else
		generator="Unix Makefiles"
		# If a default architecture is set, use it. Otherwise, use the host architecture
		if [ -z "$default_buildArch" ]; then
			getMachineArch default_arch
		else
			default_arch="$default_buildArch"
		fi
		supportedArchs+=("${default_arch}")
	fi
fi
getOS platform

outputFolder=""
buildConfig="Release"
buildConfigOverride=0
doCleanup=1
doRebuild=1
doSign=1
listArchs=0
useAllArchs=0
gen_cmake_additional_options=()
cmake_additional_options=()
marketing_version=""
betaTagName="${default_betaTagName}"

while [ $# -gt 0 ]
do
	case "$1" in
		-h)
			echo "Usage: gen_plugin_archive.sh [options]"
			echo " -h -> Display this help"
			echo " -v -> Print script version and exit"
			echo " -vvv -> Verbose mode"
			echo " -a <flags> -> Add cmake flags directly passed to underlying gen_cmake.sh"
			echo " -b <cmake path> -> Force cmake binary path (Default: $cmake_path)"
			echo " -c <cmake generator> -> Force cmake generator (Default: $generator)"
			echo " -d <deliverables folder> -> Force deliverables output folder (Default: $deliverablesFolder)"
			echo " -p <plugin name> -> Force plugin name (Default: $pluginName)"
			echo " -arch <arch> -> Set target architecture (Default: $default_arch). Supported archs depends on target platform"
			echo " -archs -> List supported architectures (which depends on target platform)"
			echo " -all-archs -> Build all supported architectures"
			echo " -no-clean -> Don't remove temp build folder [Default=clean on successful build]"
			echo " -no-rebuild -> Don't rebuild the whole solution [Default=rebuild everything]"
			if isWindows; then
				echo " -t <visual toolset> -> Force visual toolset (Default: $toolset)"
				echo " -tc <visual toolchain> -> Force visual toolchain (Default: $toolchain)"
			fi
			echo " -no-signing -> Do not sign binaries (Default: Do signing)"
			echo " -debug -> Compile using Debug configuration (Default: Release)"
			echo " -marketing-version <Version> -> Set the marketing version to use (Default: Generated from CMakeLists.txt)"
			echo " -beta-tag <BetaTag> -> Set the beta tag to use before the 4th digit (Default: $default_betaTagName)"
			if [[ $(type -t extend_gpa_fnc_help) == function ]]; then
				extend_gpa_fnc_help
			fi
			exit 3
			;;
		-v)
			exit 0
			;;
		-vvv)
			verbose=1
			;;
		-a)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -a option, see help (-h)"
				exit 4
			fi
			cmake_additional_options+=("$1")
			;;
		-b)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -b option, see help (-h)"
				exit 4
			fi
			if [ ! -x "$1" ]; then
				echo "ERROR: Specified cmake binary is not valid (not found or not executable): $1"
				exit 4
			fi
			cmake_path="$1"
			;;
		-c)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -c option, see help (-h)"
				exit 4
			fi
			cmake_generator="$1" # Update local value, we need it later
			gen_cmake_additional_options+=("-c")
			gen_cmake_additional_options+=("$1")
			;;
		-d)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -d option, see help (-h)"
				exit 4
			fi
			deliverablesFolder="$1"
			;;
		-p)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -p option, see help (-h)"
				exit 4
			fi
			pluginName="$1"
			;;
		-arch)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -arch option, see help (-h)"
				exit 4
			fi
			arch="$1"
			gen_cmake_additional_options+=("-arch")
			gen_cmake_additional_options+=("$arch")
			;;
		-archs)
			listArchs=1
			;;
		-all-archs)
			useAllArchs=1
			gen_cmake_additional_options+=("-all-archs")
			;;
		-no-clean)
			doCleanup=0
			;;
		-no-rebuild)
			doRebuild=0
			;;
		-t)
			if isWindows; then
				shift
				if [ $# -lt 1 ]; then
					echo "ERROR: Missing parameter for -t option, see help (-h)"
					exit 4
				fi
				toolset="$1" # Update local value, we need it later
				gen_cmake_additional_options+=("-t")
				gen_cmake_additional_options+=("$1")
			else
				echo "ERROR: -t option is only supported on Windows platform"
				exit 4
			fi
			;;
		-tc)
			if isWindows; then
				shift
				if [ $# -lt 1 ]; then
					echo "ERROR: Missing parameter for -tc option, see help (-h)"
					exit 4
				fi
				gen_cmake_additional_options+=("-tc")
				gen_cmake_additional_options+=("$1")
			else
				echo "ERROR: -tc option is only supported on Windows platform"
				exit 4
			fi
			;;
		-no-signing)
			doSign=0
			;;
		-debug)
			buildConfig="Debug"
			buildConfigOverride=1
			;;
		-marketing-version)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -marketing-version option, see help (-h)"
				exit 4
			fi
			marketing_version="$1"
			;;
		-beta-tag)
			shift
			if [ $# -lt 1 ]; then
				echo "ERROR: Missing parameter for -beta-tag option, see help (-h)"
				exit 4
			fi
			betaTagName="$1"
			;;
		*)
			consumed_args=0
			if [[ $(type -t extend_gpa_fnc_unhandled_arg) == function ]]; then
				extend_gpa_fnc_unhandled_arg $@
				consumed_args=$?
				for (( i=1; i<$consumed_args; i++ )); do
					shift
				done
			fi
			if [ $consumed_args -eq 0 ]; then
				echo "ERROR: Unknown option '$1' (use -h for help)"
				exit 4
			fi
			;;
	esac
	shift
done

if [[ $(type -t extend_gpa_fnc_postparse) == function ]]; then
	extend_gpa_fnc_postparse
fi

# Ensure deliverablesFolder ends with /
if [[ ${deliverablesFolder: -1} != "/" ]]; then
	deliverablesFolder="$deliverablesFolder/"
fi

# Ensure deliverablesFolder does not exist (neither file nor directory)
if [ -e "${deliverablesFolder%/*}" ]; then
	if [ -f "${deliverablesFolder%/*}" ];
	then
		echo "ERROR: Deliverables folder '$deliverablesFolder' already exists and is a file"
		exit 4
	fi
	if ! isEmptyFolder "$deliverablesFolder";
	then
		echo "ERROR: Deliverables folder '$deliverablesFolder' already exists and is not empty"
		exit 4
	fi
fi

# Create deliverablesFolder
mkdir -p "$deliverablesFolder"

if [ ! -z "$cmake_generator" ]; then
	echo "Overriding default cmake generator ($generator) with: $cmake_generator"
	generator="$cmake_generator"
fi

# Check for macOS generator when using macOS >= 13
if isMac; then
	macvers="$(sw_vers -productVersion)"
	if [[ ${macvers%%.*} -ge 13 && "${generator}" == "Xcode" ]];
	then
		echo "Xcode generator is unstable starting with macOS Ventura, please use ninja instead (-c Ninja)"
		exit 4
	fi
fi

# Remove duplicates from supported archs
removeDuplicates supportedArchs

# List supported archs
if [ $listArchs -eq 1 ]; then
	echo "Supported archs for platform ${platform} (Default arch marked with [*]):"
	for arch in "${supportedArchs[@]}";	do
		if [[ " ${default_arch[@]} " =~ " ${arch} " ]]; then
			echo " [*] $arch"
		else
			echo "     $arch"
		fi
	done
	exit 0
fi

# Use all archs
if [ $useAllArchs -eq 1 ]; then
	arch=("${supportedArchs[@]}")
fi

# No arch was specified on command line, use default arch
if [ ${#arch[*]} -eq 0 ]; then
	arch=(${default_arch[@]})
	for a in "${arch[@]}";	do
		gen_cmake_additional_options+=("-arch")
		gen_cmake_additional_options+=("$a")
	done
fi

# Check arch(s) is(are) valid for target platform
for a in "${arch[@]}";	do
	if [[ ! " ${supportedArchs[@]} " =~ " ${a} " ]]; then
		echo "ERROR: Unsupported arch for platform ${platform}: ${a} (Supported archs: ${supportedArchs[@]})"
		exit 4
	fi
done

# Concatenate all archs into one string
printf -v arch_list "%s_" "${arch[@]}"
arch_list="${arch_list%_}"

# Forward more parameters to gen_cmake
if [ ! -z "$marketing_version" ]; then
	gen_cmake_additional_options+=("-marketing-version")
	gen_cmake_additional_options+=("$marketing_version")
fi
if [ ! -z "$betaTagName" ]; then
	gen_cmake_additional_options+=("-beta-tag")
	gen_cmake_additional_options+=("$betaTagName")
fi

# Load config file
loadConfigFile

# Check for signing
if [ $doSign -eq 1 ]; then
	gen_cmake_additional_options+=("-sign")

	# Check if signing tool and signtool options are specified on windows (optional, gen_cmake will use its default values otherwise)
	if isWindows; then
		signingTool=${params["signing_tool"]}
		if [ ! -z "$signingTool" ]; then
			gen_cmake_additional_options+=("-signing-tool")
			gen_cmake_additional_options+=("$signingTool")
		fi
		signtoolOptions=${params["signtool_options"]}
		if [ ! -z "$signtoolOptions" ]; then
			gen_cmake_additional_options+=("-signtool-opt")
			gen_cmake_additional_options+=("$signtoolOptions")
		fi
	fi

	# Check if Identity is specified on macOS (optional, gen_cmake will autodetect otherwise)
	if isMac; then
		identityString="${params["identity"]}"
		if [ ! -z "$identityString" ]; then
			gen_cmake_additional_options+=("-id")
			gen_cmake_additional_options+=("$identityString")
		fi
	fi
fi

getOutputFolder outputFolder "${outputFolderBasePath}" "${platform}" "${arch_list}" "${toolset}" "${buildConfig}" "${generator}"

toolset_option=""
if [ ! -z "${toolset}" ]; then
	toolset_option="-t ${toolset}"
	if [ ! -z "${toolchain}" ]; then
		toolset_option="${toolset_option} -tc ${toolchain}"
	fi
fi

# Cleanup routine
cleanup_main()
{
	if [[ $doCleanup -eq 1 && $1 -eq 0 ]]; then
		echo -n "Cleaning... "
		sleep 2
		rm -rf "${bu_gpa_callerFolderPath}${outputFolder}"
		echo "done"
	else
		echo "Not cleaning up as requested, folder '${outputFolder}' untouched"
	fi
	exit $1
}

trap 'cleanup_main $?' EXIT

if [ -z "$pluginName" ]; then
	# Get project name as fallback
	pluginName="$(grep -Po "project *\( *(\K[^\"][^ )]+|\"\K[^\"]+)" "CMakeLists.txt")"
	if [[ $pluginName == "" ]]; then
		echo "Cannot detect plugin name, please set the pluginName variable or use the -p option"
		exit 1
	fi
	pluginName="${pluginName//[$'\t\r\n']}"
	pluginName="${pluginName/#la_/}"
fi

# Get plugin version from the root CMakeLists.txt (using the caller provided version variable name if set)
if [ ! -z "$versionVarName" ]; then
	cmakeVersion=$(grep -m 1 -Po "set *\( *${versionVarName} +\K[0-9]+(\.[0-9]+)+(?= *\))" CMakeLists.txt)
else
	cmakeVersion=$(grep -m 1 -Po "set *\(.+_VERSION +\K[0-9]+(\.[0-9]+)+(?= *\))" CMakeLists.txt)
fi
if [[ $cmakeVersion == "" ]]; then
	echo "Cannot detect plugin version"
	exit 1
fi
cmakeVersion="${cmakeVersion//[$'\t\r\n']}"

# Check if we have a release or devel version
oldIFS="$IFS"
IFS='.' read -a versionSplit <<< "$cmakeVersion"
IFS="$oldIFS"

if [[ ${#versionSplit[*]} -lt 3 || ${#versionSplit[*]} -gt 4 ]]; then
	echo "Invalid plugin version (should be in the form x.y.z[.w]): $cmakeVersion"
	exit 1
fi

beta_tag=""
build_tag=""
is_release=1
releaseVersion="${versionSplit[0]}.${versionSplit[1]}.${versionSplit[2]}"
if [ ${#versionSplit[*]} -eq 4 ]; then
	beta_tag="${betaTagName}${versionSplit[3]}"
	build_tag="+$(git rev-parse --short HEAD)"
	is_release=0
fi

if isWindows; then
	# OS name based on arch
	if [ "$arch_list" == "x64" ]; then
		archiveOSName="win64"
	else
		archiveOSName="win32"
	fi
elif isMac; then
	archiveOSName="Darwin"
else
	archiveOSName="Linux"
fi

if [ -n "$marketing_version" ]; then
	archiveBaseName="${pluginName}-${marketing_version}${beta_tag}${build_tag}+${cmakeVersion}"
else
	archiveBaseName="${pluginName}-${releaseVersion}${beta_tag}${build_tag}"
fi
archiveBaseName="${archiveBaseName}+${archiveOSName}"
if [ $buildConfigOverride -eq 1 ]; then
	archiveBaseName="${archiveBaseName}+${buildConfig}"
fi

cmake_additional_options+=("-DCU_INSTALLER_NAME=${archiveBaseName}")

# Cleanup previous build folders, just in case
if [ $doRebuild -eq 1 ]; then
	rm -rf "${bu_gpa_callerFolderPath}${outputFolder}"
fi

# We must add a cmake parameter when using Single-Configuration generators
if isSingleConfigurationGenerator "$generator"; then
	gen_cmake_additional_options+=("-${buildConfig,,}")
fi

# Print build properties summary
echo "/--------------------------\\"
echo "| Plugin archive properties summary"
echo "| - CMAKE VERS: $("$cmake_path" --version | grep -oP '\d+(\.\d+)+')"
echo "| - GENERATOR: ${generator}"
echo "| - PLATFORM: ${platform}"
echo "| - ARCH: ${arch[@]}"
if [ ! -z "${toolset}" ]; then
	echo "| - TOOLSET: ${toolset}"
fi
if [ ! -z "${toolchain}" ]; then
	echo "| - TOOLCHAIN: ${toolchain}"
fi
if [ ! -z "${buildConfig}" ]; then
	echo "| - BUILD TYPE: ${buildConfig}"
fi
echo "| - PLUGIN NAME: ${pluginName}"
echo "| - PLUGIN VERSION: ${releaseVersion}${beta_tag}"
if [[ $(type -t extend_gpa_fnc_props_summary) == function ]]; then
	extend_gpa_fnc_props_summary
fi
echo "\\--------------------------/"
echo ""

# Compilation stuff
if [ $verbose -eq 1 ]; then
	echo "Running command: ./gen_cmake.sh -o \"${outputFolder}\" ${gen_cmake_additional_options[@]} $toolset_option -f \"$cmake_opt\" -- ${cmake_additional_options[@]}"
	./gen_cmake.sh -o "${outputFolder}" "${gen_cmake_additional_options[@]}" $toolset_option -f "$cmake_opt" -- "${cmake_additional_options[@]}"
	if [ $? -ne 0 ]; then
		echo "Failed to generate cmake files ;("
		exit 1
	fi
else
	echo -n "Generating cmake files... "
	log=$(./gen_cmake.sh -o "${outputFolder}" "${gen_cmake_additional_options[@]}" $toolset_option -f "$cmake_opt" -- "${cmake_additional_options[@]}")
	if [ $? -ne 0 ]; then
		echo "Failed to generate cmake files ;("
		echo ""
		echo $log
		exit 1
	fi
	echo "done"
fi

pushd "${outputFolder}" &> /dev/null
echo -n "Building plugin... "
declare -a cmakeBuildParameters=("--build" "." "-j" "4" "--config" "${buildConfig}")
if [ $doRebuild -eq 1 ]; then
	cmakeBuildParameters+=("--clean-first")
fi
log=$("${cmake_path}" "${cmakeBuildParameters[@]}")
if [ $? -ne 0 ]; then
	echo "Failed to build plugin ;("
	echo ""
	echo $log
	exit 1
fi
echo "done"
popd &> /dev/null

pushd "${outputFolder}" &> /dev/null
echo -n "Generating plugin archive... "
log=$("$cmake_path" --build . --config "${buildConfig}" --target package)
if [ $? -ne 0 ]; then
	echo "Failed to generate plugin archive ;("
	echo ""
	echo $log
	exit 1
fi
echo "done"
popd &> /dev/null

generatedArchiveFilePath="${outputFolder}/${archiveBaseName}.zip"
if [ ! -f "$generatedArchiveFilePath" ]; then
	echo "ERROR: Cannot find generated archive '${archiveBaseName}.zip' in $outputFolder sub folder. Not cleaning it so you can manually search."
	doCleanup=0
	exit 1
fi
fullArchiveName="${generatedArchiveFilePath##*/}" # Get the file name only

mv "${generatedArchiveFilePath}" "${deliverablesFolder}"

echo ""
echo "Plugin archive generated: ${fullArchiveName}"
echo "All files copied to ${deliverablesFolder}"
